PROGRAM PRINT;
USES CRT,DOS,PRINTER,U_TOOL;
VAR
  R:SEARCHREC;
  MAX:BYTE;
  MARGIN,LINES:INTEGER;

  DIRECTORYFILE:FILE OF STRING;
  PATH:STRING;
PROCEDURE LMARGIN;
VAR I:INTEGER;
BEGIN
FOR I:=1 TO MARGIN DO WRITE(LST,' ');
END;

PROCEDURE  PRINT_FILE(FNAME:STRING);
VAR
 T:TEXT;
 ST:STRING;
 I:INTEGER;
 D:CHAR;
BEGIN
 ASSIGN(T,FNAME);
 FILEMODE:=0;
 RESET(T);
 I:=0;
 WHILE NOT EOF(T) DO
 BEGIN
 INC(I);
 READLN(T,ST);
 IF I>LINES THEN BEGIN BEEP;I:=0; D:=READKEY; END;
 LMARGIN; WRITELN(LST,ST);
 END;
 CLOSE(T);
END;

PROCEDURE FIND(PATH:STRING);
VAR
T:TEXT;
ST:STRING;
D,M:CHAR;
BEGIN
 FINDFIRST(PATH,ANYFILE,R);
 WHILE DOSERROR=0 DO
 BEGIN
 WRITE('WANT TO PRINT ',R.NAME ,' (Y/N)? :');
 D:=READKEY;
 WRITELN;
 IF D IN ['Y','y'] THEN
 BEGIN
 WRITE('WANT A NEW PAGE (Y/N) ?');
 M:=READKEY;
 WRITELN;
  IF M IN ['Y','y'] THEN
  WRITE(LST,#12);

 PRINT_FILE(R.NAME);

 REPEAT
 WRITE('SPACE NEEDED  (Y/N)  ?:');
 D:=READKEY;
 WRITELN;
 IF D IN ['Y','y'] THEN
 WRITELN(LST);
 UNTIL D IN ['N','n'];


 END;

 FINDNEXT(R);
 END;
END;
BEGIN

WRITELN;
WRITELN;

 WRITE('ENTER PATH     :');
 READLN(PATH);
 WRITE('Left Margin    :'); READLN(MARGIN);
 WRITE('Lines Per Page :'); READLN(LINES);
 FIND(PATH);


END.