PROGRAM SORT_FILE(INPUT,OUTPUT);
VAR
   T:FILE OF BYTE;
   B1,B2:BYTE;
   I,J:INTEGER;
BEGIN
   ASSIGN(T,'BYTE_FIL.DAT');
   REWRITE(T);
   WRITELN(' ENTER THE NUMBERS :-');
    READ(B1);
   WHILE NOT EOF DO
   BEGIN
      WRITE(T,B1);
      READ(B1);
   END;
   CLOSE(T);
   RESET(T);

FOR I:=1 TO FILESIZE(T)-1 DO
FOR J:=I+1 TO FILESIZE(T) DO
BEGIN
  SEEK(T,I-1);
  READ(T,B1);
  SEEK(T,J-1);
  READ(T,B2);

IF B1>B2 THEN
BEGIN
  SEEK(T,I-1);
  WRITE(T,B2);
  SEEK(T,J-1);
  WRITE(T,B1);
END;
END;
 RESET(T);
 WHILE NOT EOF(T) DO
 BEGIN
  READ(T,B1);
  WRITELN(B1);
 END;
 CLOSE(T);
END.